apiVersion: v1
kind: Secret
metadata:
  name: trainbook-secrets
type: Opaque
data:
  DB_URL: bW9uZ29kYitzcnY6Ly9Zb3VyVXNlcm5hbWU6WU9VUlBBU1NXT1JEQHlvdXJjbHVzdGVyLWRiaG9zdC1jbHVzdGVyLmNpdHdmNW4ubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPVlvdXJEYXRhYmFzZS1DbHVzdGVyLU5hbWU=
  DB_NAME: cmVzZXJ2YXRpb24=  # 'reservation' encoded in base64
